peakProgram: peaksearch
threshold: 0.05
thresholdRatio: -1
maxRfactor: 0.5
boxsize: 10
max_number: 300
min_separation: 10
peakShape: Lorentzian
#scanPointStart: 285
#scanPointEnd: 286
#depthRangeStart: 35
#depthRangeEnd: 36
detectorCropX1: 0 #min 0 max 2047
detectorCropX2: 2047
detectorCropY1: 0
detectorCropY2: 2047
min_size: 1.13
max_peaks: 300
smooth: 0
maskFile: ''
indexKeVmaxCalc: 18.2
indexKeVmaxTest: 40.0
indexAngleTolerance: 0.1
indexH: 1
indexK: 1
indexL: 1
indexCone: 72.0
energyUnit: keV
exposureUnit: sec
cosmicFilter: True
recipLatticeUnit: 1/nm
latticeParametersUnit: nm
indexProgram: euler
pathbins: /eagle/APSDataAnalysis/hparraga/laue-indexing
outputFolder: /eagle/APSDataAnalysis/hparraga/laue-indexing/output
filefolder: /eagle/APSDataAnalysis/LAUE/repacks_manual/repacks_100mn_thresh_10/consgeo_Ni2_100mN_285
#filefolder: /eagle/APSDataAnalysis/hparraga/test/consgeo_Ni2_100mN_285
filenamePrefix: out_
geoFile: /eagle/APSDataAnalysis/hparraga/laue-indexing/pipeline/config/geoN_2023-02-07_19-19-10.xml
crystFile: /eagle/APSDataAnalysis/hparraga/laue-indexing/pipeline/config/Ni.xml